In [4]:
#3x3 matrix
import numpy as np

In [2]:
a=[[1, 2, 5],[4,2,6],[6,7,8]]
print(a)

[[1, 2, 5], [4, 2, 6], [6, 7, 8]]


In [18]:
#need only 2x2 from a
m=np.array(a)
print(m)

[[1 2 5]
 [4 2 6]
 [6 7 8]]


In [19]:
b=m[0:2,0:2]
print(b)

[[1 2]
 [4 2]]
